name: Build caddy-cf-ddns-csec-geoip

on:
  workflow_dispatch:  # allows to run the workflow manually from the Actions tab
  push:
    branches: 
      - main # Set a branch to deploy when pushed
    paths:
      - caddy-cloudflare-ddns-crowdsec/Dockerfile

env:
  DOCKER_BUILDKIT: 1
  DOCKER_NAME: caddy-cf-ddns-csec-geoip
  DOCKER_DESCRIPTION: "Caddy Docker custom build with Cloudflare Dynamic DNS/IPs, CrowdSec Bouncer modules and MaxMind GeoIP"

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish container image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./${{ env.DOCKER_NAME }}/Dockerfile
          push: true
          provenance: false
          tags: rupes17/caddy-cf-ddns-csec-geoip:latest