name: Deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - main # Set a branch to deploy when pushed
    paths:
      - caddy-cf-ddns-csec-geoip/Dockerfile

env:
  DOCKER_BUILDKIT: 1
  DOCKER_NAME: caddy-cf-ddns-csec-geoip
  DOCKER_DESCRIPTION: "Caddy Docker custom build with Cloudflare Dynamic DNS/IPs, CrowdSec Bouncer modules and MaxMind GeoIP"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm install

      - name: Run Typecheck
        run: npm run typecheck

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ env.DOCKER_NAME }}/Dockerfile
          push: true
          provenance: false
          tags: rupes17/caddy-cf-ddns-csec-geoip:latest